#!/usr/bin/python3

if __name__ == "__main__":
    devDependencies = {
        "babel-core": "^6.26.0",
        "babel-loader": "^7.1.2",
        "babel-plugin-transform-runtime": "^6.23.0",
        "babel-preset-es2015": "^6.24.1",
        "babel-preset-stage-3": "^6.24.1",
        "glob": "^7.1.3",
        "redux-devtools-extension": "^2.13.5",
        "serve": "^11.3.2",
        "serverless-webpack": "^5.2.0",
        "webpack": "^5.36.2",
        "webpack-node-externals": "^1.7.2"
    }
    dependencies = {
        "ajv": "^6.5.5",
        "autoprefixer": "7.1.6",
        "axios": "^0.21.1",
        "babel-core": "6.26.0",
        "babel-eslint": "7.2.3",
        "babel-jest": "^26.6.3",
        "babel-loader": "7.1.2",
        "babel-preset-react-app": "^3.1.2",
        "babel-runtime": "^6.26.0",
        "case-sensitive-paths-webpack-plugin": "2.1.1",
        "chalk": "1.1.3",
        "css-loader": "^5.2.4",
        "dotenv": "4.0.0",
        "dotenv-expand": "4.2.0",
        "eslint": "4.10.0",
        "eslint-config-react-app": "^2.1.0",
        "eslint-loader": "1.9.0",
        "eslint-plugin-flowtype": "2.39.1",
        "eslint-plugin-import": "2.8.0",
        "eslint-plugin-jsx-a11y": "5.1.1",
        "eslint-plugin-react": "7.4.0",
        "extract-text-webpack-plugin": "3.0.2",
        "file-loader": "1.1.5",
        "fs-extra": "3.0.1",
        "highcharts": "^9.1.0",
        "highcharts-react-official": "github:highcharts/highcharts-react",
        "history": "^4.7.2",
        "html-webpack-plugin": "2.29.0",
        "jest": "^26.6.3",
        "jquery": "^3.3.1",
        "moment": "^2.22.2",
        "node-sass": "^4.10.0",
        "numeral": "^2.0.6",
        "object-assign": "4.1.1",
        "postcss-flexbugs-fixes": "3.2.0",
        "postcss-loader": "2.0.8",
        "promise": "8.0.1",
        "raf": "3.4.0",
        "react": "^16.6.1",
        "react-bootstrap": "^0.32.4",
        "react-bs-notifier": "^4.4.6",
        "react-circular-progressbar": "^0.8.1",
        "react-datepicker": "^1.8.0",
        "react-dates": "^16.7.1",
        "react-dev-utils": ">=11.0.4",
        "react-dom": "^16.6.1",
        "react-notifications": "^1.4.3",
        "react-redux": "^5.1.0",
        "react-router-dom": "^4.3.1",
        "react-router-redux": "^5.0.0-alpha.9",
        "react-select": "^1.3.0",
        "react-select2": "^4.0.3",
        "react-table": "^6.8.6",
        "react-toggle-component": "^1.0.4",
        "redux": "^3.7.2",
        "redux-thunk": "^2.3.0",
        "sass-loader": "^6.0.6",
        "select2": "^4.0.6-rc.1",
        "style-loader": "0.19.0",
        "sw-precache-webpack-plugin": "0.11.4",
        "url-loader": "0.6.2",
        "webpack-dev-server": "^3.11.2",
        "webpack-manifest-plugin": "1.3.2",
        "whatwg-fetch": "2.0.3"
    }
    output = "yarn add -D "
    for key in devDependencies:
        output += f'{key} '
    print(output)
